// @pluralscape/sync/protocol — Full sync protocol message taxonomy
export type {
  TransportState,
  SyncTransport,
  SyncMessageBase,
  DocumentVersionEntry,
  DocumentCatchup,
  SyncErrorCode,
  AuthenticateRequest,
  ManifestRequest,
  SubscribeRequest,
  UnsubscribeRequest,
  FetchSnapshotRequest,
  FetchChangesRequest,
  SubmitChangeRequest,
  SubmitSnapshotRequest,
  DocumentLoadRequest,
  AuthenticateResponse,
  ManifestResponse,
  SubscribeResponse,
  DocumentUpdate,
  SnapshotResponse,
  ChangesResponse,
  ChangeAccepted,
  SnapshotAccepted,
  ManifestChanged,
  SyncError,
  ClientMessage,
  ServerMessage,
  SyncMessage,
} from "./protocol.js";
export { SYNC_PROTOCOL_VERSION } from "./protocol.js";
