// AUTO-GENERATED by tokens/build.mjs. DO NOT EDIT BY HAND.
// SoT: tokens/*.json. Run `pnpm tokens:build` to regenerate.

export type Theme = {
  color: {
    accent: string;
    accentActive: string;
    accentHover: string;
    bg: string;
    bgSubtle: string;
    border: string;
    borderFocus: string;
    borderStrong: string;
    danger: string;
    fg: string;
    fgMuted: string;
    fgOnAccent: string;
    fgSubtle: string;
    interactiveOn: string;
    intimate: string;
    linkColor: string;
    linkHover: string;
    success: string;
    surface: string;
    surfaceHover: string;
    warning: string;
  };
  font: {
    mono: string;
    sans: string;
  };
  scale: {
    body: {
      lh: number;
      ls: number;
      size: number;
      weight: number;
    };
    bodySm: {
      lh: number;
      ls: number;
      size: number;
      weight: number;
    };
    caption: {
      lh: number;
      ls: number;
      size: number;
      weight: number;
    };
    display: {
      lh: number;
      ls: number;
      size: number;
      weight: number;
    };
    h1: {
      lh: number;
      ls: number;
      size: number;
      weight: number;
    };
    h2: {
      lh: number;
      ls: number;
      size: number;
      weight: number;
    };
    h3: {
      lh: number;
      ls: number;
      size: number;
      weight: number;
    };
    label: {
      lh: number;
      ls: number;
      size: number;
      weight: number;
    };
  };
  space: {
    "2xl": number;
    lg: number;
    md: number;
    sm: number;
    xl: number;
    xs: number;
  };
  hit: {
    comfy: number;
    dense: number;
    min: number;
  };
  radius: {
    full: number;
    lg: number;
    md: number;
    sm: number;
  };
  motion: {
    ease: string;
    dur: {
      micro: number;
      page: number;
      transition: number;
    };
  };
  elevation: {
    shadow: {
      lg: string;
      md: string;
      sm: string;
    };
    glow: {
      lavender: string;
      teal: string;
    };
  };
};

export type ThemeMode = "default" | "static" | "reduced-motion" | "high-contrast" | "littles";

export const themes = {
  default: {
    color: {
      accent: "#b8a9c9",
      accentActive: "#ae9fbf",
      accentHover: "#d6c5e6",
      bg: "#0f0f23",
      bgSubtle: "#12122a",
      border: "#2a2a4a",
      borderFocus: "#c9bcda",
      borderStrong: "#8780ad",
      danger: "#e88691",
      fg: "#e8e4f0",
      fgMuted: "#a8a4b8",
      fgOnAccent: "#0f0f23",
      fgSubtle: "#908aa5",
      interactiveOn: "#b8a9c9",
      intimate: "#d4a5b5",
      linkColor: "#c9bcda",
      linkHover: "#dcd0eb",
      success: "#7ecbc0",
      surface: "#181833",
      surfaceHover: "#1f1f3f",
      warning: "#d4b05a",
    },
    font: {
      mono: "'JetBrains Mono', 'Fira Code', ui-monospace, SFMono-Regular, Menlo, monospace",
      sans: "'DM Sans', Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    },
    scale: {
      body: {
        lh: 1.5,
        ls: 0,
        size: 16,
        weight: 400,
      },
      bodySm: {
        lh: 1.5,
        ls: 0,
        size: 14,
        weight: 400,
      },
      caption: {
        lh: 1.4,
        ls: 0.2,
        size: 12,
        weight: 400,
      },
      display: {
        lh: 1.2,
        ls: 0.5,
        size: 32,
        weight: 300,
      },
      h1: {
        lh: 1.3,
        ls: 0.3,
        size: 24,
        weight: 400,
      },
      h2: {
        lh: 1.3,
        ls: 0.2,
        size: 20,
        weight: 500,
      },
      h3: {
        lh: 1.4,
        ls: 0.1,
        size: 16,
        weight: 500,
      },
      label: {
        lh: 1.2,
        ls: 0.5,
        size: 12,
        weight: 500,
      },
    },
    space: {
      "2xl": 48,
      lg: 24,
      md: 16,
      sm: 8,
      xl: 32,
      xs: 4,
    },
    hit: {
      comfy: 48,
      dense: 32,
      min: 44,
    },
    radius: {
      full: 9999,
      lg: 16,
      md: 12,
      sm: 6,
    },
    motion: {
      ease: "cubic-bezier(0.4, 0, 0.2, 1)",
      dur: {
        micro: 150,
        page: 400,
        transition: 250,
      },
    },
    elevation: {
      shadow: {
        lg: "0 16px 48px rgba(0, 0, 0, 0.55)",
        md: "0 4px 16px rgba(0, 0, 0, 0.45), 0 0 0 1px #2a2a4a inset",
        sm: "0 1px 2px rgba(0, 0, 0, 0.35)",
      },
      glow: {
        lavender: "0 0 24px rgba(184, 169, 201, 0.25)",
        teal: "0 0 24px rgba(126, 203, 192, 0.25)",
      },
    },
  } as const satisfies Theme,
  static: {
    color: {
      accent: "#b8a9c9",
      accentActive: "#ae9fbf",
      accentHover: "#d6c5e6",
      bg: "#0f0f23",
      bgSubtle: "#0f0f23",
      border: "#3a3a5a",
      borderFocus: "#c9bcda",
      borderStrong: "#8780ad",
      danger: "#e88691",
      fg: "#e8e4f0",
      fgMuted: "#a8a4b8",
      fgOnAccent: "#0f0f23",
      fgSubtle: "#908aa5",
      interactiveOn: "#b8a9c9",
      intimate: "#d4a5b5",
      linkColor: "#c9bcda",
      linkHover: "#dcd0eb",
      success: "#7ecbc0",
      surface: "#161629",
      surfaceHover: "#181833",
      warning: "#d4b05a",
    },
    font: {
      mono: "'JetBrains Mono', 'Fira Code', ui-monospace, SFMono-Regular, Menlo, monospace",
      sans: "'DM Sans', Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    },
    scale: {
      body: {
        lh: 1.5,
        ls: 0,
        size: 16,
        weight: 400,
      },
      bodySm: {
        lh: 1.5,
        ls: 0,
        size: 14,
        weight: 400,
      },
      caption: {
        lh: 1.4,
        ls: 0.2,
        size: 12,
        weight: 400,
      },
      display: {
        lh: 1.2,
        ls: 0.5,
        size: 32,
        weight: 300,
      },
      h1: {
        lh: 1.3,
        ls: 0.3,
        size: 24,
        weight: 400,
      },
      h2: {
        lh: 1.3,
        ls: 0.2,
        size: 20,
        weight: 500,
      },
      h3: {
        lh: 1.4,
        ls: 0.1,
        size: 16,
        weight: 500,
      },
      label: {
        lh: 1.2,
        ls: 0.5,
        size: 12,
        weight: 500,
      },
    },
    space: {
      "2xl": 48,
      lg: 24,
      md: 16,
      sm: 8,
      xl: 32,
      xs: 4,
    },
    hit: {
      comfy: 48,
      dense: 32,
      min: 44,
    },
    radius: {
      full: 9999,
      lg: 16,
      md: 12,
      sm: 6,
    },
    motion: {
      ease: "cubic-bezier(0.4, 0, 0.2, 1)",
      dur: {
        micro: 0,
        page: 0,
        transition: 0,
      },
    },
    elevation: {
      shadow: {
        lg: "0 16px 48px rgba(0, 0, 0, 0.55)",
        md: "0 4px 16px rgba(0, 0, 0, 0.45), 0 0 0 1px #2a2a4a inset",
        sm: "0 1px 2px rgba(0, 0, 0, 0.35)",
      },
      glow: {
        lavender: "none",
        teal: "none",
      },
    },
  } as const satisfies Theme,
  "reduced-motion": {
    color: {
      accent: "#b8a9c9",
      accentActive: "#ae9fbf",
      accentHover: "#d6c5e6",
      bg: "#0f0f23",
      bgSubtle: "#12122a",
      border: "#2a2a4a",
      borderFocus: "#c9bcda",
      borderStrong: "#8780ad",
      danger: "#e88691",
      fg: "#e8e4f0",
      fgMuted: "#a8a4b8",
      fgOnAccent: "#0f0f23",
      fgSubtle: "#908aa5",
      interactiveOn: "#b8a9c9",
      intimate: "#d4a5b5",
      linkColor: "#c9bcda",
      linkHover: "#dcd0eb",
      success: "#7ecbc0",
      surface: "#181833",
      surfaceHover: "#1f1f3f",
      warning: "#d4b05a",
    },
    font: {
      mono: "'JetBrains Mono', 'Fira Code', ui-monospace, SFMono-Regular, Menlo, monospace",
      sans: "'DM Sans', Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    },
    scale: {
      body: {
        lh: 1.5,
        ls: 0,
        size: 16,
        weight: 400,
      },
      bodySm: {
        lh: 1.5,
        ls: 0,
        size: 14,
        weight: 400,
      },
      caption: {
        lh: 1.4,
        ls: 0.2,
        size: 12,
        weight: 400,
      },
      display: {
        lh: 1.2,
        ls: 0.5,
        size: 32,
        weight: 300,
      },
      h1: {
        lh: 1.3,
        ls: 0.3,
        size: 24,
        weight: 400,
      },
      h2: {
        lh: 1.3,
        ls: 0.2,
        size: 20,
        weight: 500,
      },
      h3: {
        lh: 1.4,
        ls: 0.1,
        size: 16,
        weight: 500,
      },
      label: {
        lh: 1.2,
        ls: 0.5,
        size: 12,
        weight: 500,
      },
    },
    space: {
      "2xl": 48,
      lg: 24,
      md: 16,
      sm: 8,
      xl: 32,
      xs: 4,
    },
    hit: {
      comfy: 48,
      dense: 32,
      min: 44,
    },
    radius: {
      full: 9999,
      lg: 16,
      md: 12,
      sm: 6,
    },
    motion: {
      ease: "cubic-bezier(0.4, 0, 0.2, 1)",
      dur: {
        micro: 50,
        page: 50,
        transition: 50,
      },
    },
    elevation: {
      shadow: {
        lg: "0 16px 48px rgba(0, 0, 0, 0.55)",
        md: "0 4px 16px rgba(0, 0, 0, 0.45), 0 0 0 1px #2a2a4a inset",
        sm: "0 1px 2px rgba(0, 0, 0, 0.35)",
      },
      glow: {
        lavender: "0 0 24px rgba(184, 169, 201, 0.25)",
        teal: "0 0 24px rgba(126, 203, 192, 0.25)",
      },
    },
  } as const satisfies Theme,
  "high-contrast": {
    color: {
      accent: "#d6c8e6",
      accentActive: "#c6b8d6",
      accentHover: "#ece0f5",
      bg: "#0f0f23",
      bgSubtle: "#0f0f23",
      border: "#9089b6",
      borderFocus: "#ffffff",
      borderStrong: "#b8b1d8",
      danger: "#e88691",
      fg: "#ffffff",
      fgMuted: "#e8e4f0",
      fgOnAccent: "#0f0f23",
      fgSubtle: "#a8a4b8",
      interactiveOn: "#d6c8e6",
      intimate: "#d4a5b5",
      linkColor: "#ffffff",
      linkHover: "#e8e4f0",
      success: "#7ecbc0",
      surface: "#0f0f23",
      surfaceHover: "#1a1a35",
      warning: "#d4b05a",
    },
    font: {
      mono: "'JetBrains Mono', 'Fira Code', ui-monospace, SFMono-Regular, Menlo, monospace",
      sans: "'DM Sans', Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    },
    scale: {
      body: {
        lh: 1.5,
        ls: 0,
        size: 16,
        weight: 500,
      },
      bodySm: {
        lh: 1.5,
        ls: 0,
        size: 14,
        weight: 500,
      },
      caption: {
        lh: 1.4,
        ls: 0.2,
        size: 12,
        weight: 400,
      },
      display: {
        lh: 1.2,
        ls: 0.5,
        size: 32,
        weight: 300,
      },
      h1: {
        lh: 1.3,
        ls: 0.3,
        size: 24,
        weight: 400,
      },
      h2: {
        lh: 1.3,
        ls: 0.2,
        size: 20,
        weight: 500,
      },
      h3: {
        lh: 1.4,
        ls: 0.1,
        size: 16,
        weight: 500,
      },
      label: {
        lh: 1.2,
        ls: 0.5,
        size: 12,
        weight: 500,
      },
    },
    space: {
      "2xl": 48,
      lg: 24,
      md: 16,
      sm: 8,
      xl: 32,
      xs: 4,
    },
    hit: {
      comfy: 56,
      dense: 40,
      min: 48,
    },
    radius: {
      full: 9999,
      lg: 16,
      md: 12,
      sm: 6,
    },
    motion: {
      ease: "cubic-bezier(0.4, 0, 0.2, 1)",
      dur: {
        micro: 100,
        page: 250,
        transition: 150,
      },
    },
    elevation: {
      shadow: {
        lg: "0 16px 48px rgba(0, 0, 0, 0.55)",
        md: "0 4px 16px rgba(0, 0, 0, 0.45), 0 0 0 1px #2a2a4a inset",
        sm: "0 1px 2px rgba(0, 0, 0, 0.35)",
      },
      glow: {
        lavender: "none",
        teal: "none",
      },
    },
  } as const satisfies Theme,
  littles: {
    color: {
      accent: "#d4a5b5",
      accentActive: "#c79aac",
      accentHover: "#dcb1c0",
      bg: "#0f0f23",
      bgSubtle: "#12122a",
      border: "#2a2a4a",
      borderFocus: "#d4a5b5",
      borderStrong: "#8780ad",
      danger: "#b67079",
      fg: "#e8e4f0",
      fgMuted: "#a8a4b8",
      fgOnAccent: "#0f0f23",
      fgSubtle: "#908aa5",
      interactiveOn: "#d4a5b5",
      intimate: "#d4a5b5",
      linkColor: "#c9bcda",
      linkHover: "#dcd0eb",
      success: "#7ecbc0",
      surface: "#1c1832",
      surfaceHover: "#1f1f3f",
      warning: "#d4b05a",
    },
    font: {
      mono: "'JetBrains Mono', 'Fira Code', ui-monospace, SFMono-Regular, Menlo, monospace",
      sans: "'DM Sans', Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    },
    scale: {
      body: {
        lh: 1.5,
        ls: 0,
        size: 18,
        weight: 400,
      },
      bodySm: {
        lh: 1.5,
        ls: 0,
        size: 16,
        weight: 400,
      },
      caption: {
        lh: 1.4,
        ls: 0.2,
        size: 12,
        weight: 400,
      },
      display: {
        lh: 1.2,
        ls: 0.5,
        size: 32,
        weight: 300,
      },
      h1: {
        lh: 1.3,
        ls: 0.3,
        size: 24,
        weight: 400,
      },
      h2: {
        lh: 1.3,
        ls: 0.2,
        size: 20,
        weight: 500,
      },
      h3: {
        lh: 1.4,
        ls: 0.1,
        size: 16,
        weight: 500,
      },
      label: {
        lh: 1.2,
        ls: 0.5,
        size: 13,
        weight: 500,
      },
    },
    space: {
      "2xl": 48,
      lg: 24,
      md: 16,
      sm: 8,
      xl: 32,
      xs: 4,
    },
    hit: {
      comfy: 64,
      dense: 48,
      min: 56,
    },
    radius: {
      full: 9999,
      lg: 16,
      md: 12,
      sm: 6,
    },
    motion: {
      ease: "cubic-bezier(0.4, 0, 0.2, 1)",
      dur: {
        micro: 150,
        page: 400,
        transition: 250,
      },
    },
    elevation: {
      shadow: {
        lg: "0 16px 48px rgba(0, 0, 0, 0.55)",
        md: "0 4px 16px rgba(0, 0, 0, 0.45), 0 0 0 1px #2a2a4a inset",
        sm: "0 1px 2px rgba(0, 0, 0, 0.35)",
      },
      glow: {
        lavender: "0 0 24px rgba(184, 169, 201, 0.25)",
        teal: "0 0 24px rgba(126, 203, 192, 0.25)",
      },
    },
  } as const satisfies Theme,
} as const satisfies Record<ThemeMode, Theme>;
