// AUTO-GENERATED by tokens/build.mjs. DO NOT EDIT BY HAND.
// SoT: tokens/*.json. Run `pnpm tokens:build` to regenerate.

export const palette = {
  primary: {
    deepSpaceBlue: "#0f0f23",
    moonlight: "#e8e4f0",
    paleRose: "#d4a5b5",
    skyTeal: "#7ecbc0",
    softLavender: "#b8a9c9",
  },
  extended: {
    darkLavender: "#6b5d87",
    darkTeal: "#2d7a72",
    dimMoonlight: "#a8a4b8",
    dustyCrimson: "#b67079",
    lavenderBright: "#c9bcda",
    lavenderHi: "#d6c5e6",
    nebula: "#12122a",
    paleAmber: "#d4b05a",
    softCrimson: "#e88691",
    spaceMist: "#181833",
    stardust: "#908aa5",
    surfaceHover: "#1f1f3f",
    twilight: "#2a2a4a",
  },
} as const;

export const typography = {
  font: {
    mono: "'JetBrains Mono', 'Fira Code', ui-monospace, SFMono-Regular, Menlo, monospace",
    sans: "'DM Sans', Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  },
  scale: {
    body: {
      lh: 1.5,
      ls: 0,
      size: 16,
      weight: 400,
    },
    bodySm: {
      lh: 1.5,
      ls: 0,
      size: 14,
      weight: 400,
    },
    caption: {
      lh: 1.4,
      ls: 0.2,
      size: 12,
      weight: 400,
    },
    display: {
      lh: 1.2,
      ls: 0.5,
      size: 32,
      weight: 300,
    },
    h1: {
      lh: 1.3,
      ls: 0.3,
      size: 24,
      weight: 400,
    },
    h2: {
      lh: 1.3,
      ls: 0.2,
      size: 20,
      weight: 500,
    },
    h3: {
      lh: 1.4,
      ls: 0.1,
      size: 16,
      weight: 500,
    },
    label: {
      lh: 1.2,
      ls: 0.5,
      size: 12,
      weight: 500,
    },
  },
} as const;

export const spacing = {
  "2xl": 48,
  lg: 24,
  md: 16,
  sm: 8,
  xl: 32,
  xs: 4,
} as const;

export const hit = {
  comfy: 48,
  dense: 32,
  min: 44,
} as const;

export const radius = {
  full: 9999,
  lg: 16,
  md: 12,
  sm: 6,
} as const;

export const motion = {
  ease: "cubic-bezier(0.4, 0, 0.2, 1)",
  dur: {
    micro: 150,
    page: 400,
    transition: 250,
  },
} as const;

export const elevation = {
  shadow: {
    lg: "0 16px 48px rgba(0, 0, 0, 0.55)",
    md: "0 4px 16px rgba(0, 0, 0, 0.45), 0 0 0 1px #2a2a4a inset",
    sm: "0 1px 2px rgba(0, 0, 0, 0.35)",
  },
  glow: {
    lavender: "0 0 24px rgba(184, 169, 201, 0.25)",
    teal: "0 0 24px rgba(126, 203, 192, 0.25)",
  },
} as const;
