/**
 * Wire protocol shared between the main-thread OPFS driver proxy and the
 * Web Worker hosting wa-sqlite + OPFSCoopSyncVFS.
 *
 * All messages are structured-clone-safe. Uint8Array blobs ride natively.
 */

/** Value types that can be bound as SQL parameters or returned as column values. */
export type BindParam = number | string | bigint | Uint8Array | null;

/** Row object returned from all()/get() — column name to value. */
export type Row = Record<string, BindParam>;

/** Opaque prepared-statement handle. Generated by the worker. */
export type StmtHandle = number;

// ── Requests: main → worker ───────────────────────────────────────────

export type Req =
  | { id: number; kind: "init" }
  | { id: number; kind: "prepare"; sql: string }
  | { id: number; kind: "run"; stmt: StmtHandle; params: BindParam[] }
  | { id: number; kind: "all"; stmt: StmtHandle; params: BindParam[] }
  | { id: number; kind: "get"; stmt: StmtHandle; params: BindParam[] }
  | { id: number; kind: "exec"; sql: string }
  | { id: number; kind: "txn-begin" }
  | { id: number; kind: "txn-commit" }
  | { id: number; kind: "txn-rollback" }
  | { id: number; kind: "finalize"; stmt: StmtHandle }
  | { id: number; kind: "close" };

// ── Responses: worker → main ──────────────────────────────────────────

export type OkResult = undefined | Row[] | Row | StmtHandle;

export type ErrorPayload = { message: string; code?: number; name?: string };

export type Res =
  | { id: number; ok: true; result: OkResult }
  | { id: number; ok: false; error: ErrorPayload }
  | { id: -1; ok: false; panic: true; error: ErrorPayload };

// ── Error classes ─────────────────────────────────────────────────────

export class OpfsDriverError extends Error {
  readonly code?: number;
  constructor(message: string, opts: { code?: number; name?: string; cause?: unknown } = {}) {
    super(message, opts.cause !== undefined ? { cause: opts.cause } : undefined);
    this.name = opts.name ?? "OpfsDriverError";
    if (opts.code !== undefined) this.code = opts.code;
  }
}

export class OpfsDriverUnavailableError extends Error {
  constructor(message: string, cause?: unknown) {
    super(message, cause !== undefined ? { cause } : undefined);
    this.name = "OpfsDriverUnavailableError";
  }
}

export class WorkerTerminatedError extends Error {
  constructor() {
    super("OPFS worker terminated while request was in flight");
    this.name = "WorkerTerminatedError";
  }
}
