import type { Plaintext } from "./encryption.js";
import type { AccountId, ApiKeyId, AuditLogEntryId, SystemId } from "./ids.js";
import type { UnixMillis } from "./timestamps.js";

/** Step names used in setup wizard audit events. */
export type SetupStepName = "nomenclature" | "profile";

/** The category of audit event. */
export type AuditEventType =
  | "auth.register"
  | "auth.login"
  | "auth.login-failed"
  | "auth.logout"
  | "auth.password-changed"
  | "auth.recovery-key-used"
  | "auth.key-created"
  | "auth.key-revoked"
  | "data.export"
  | "data.import"
  | "data.purge"
  | "settings.changed"
  | "member.created"
  | "member.archived"
  | "sharing.granted"
  | "sharing.revoked"
  | "bucket.key_rotation.initiated"
  | "bucket.key_rotation.chunk_completed"
  | "bucket.key_rotation.completed"
  | "bucket.key_rotation.failed"
  | "device.security.jailbreak_warning_shown"
  | "auth.password-reset-via-recovery"
  | "auth.recovery-key-regenerated"
  | "auth.device-transfer-initiated"
  | "auth.device-transfer-completed"
  | "auth.email-changed"
  | "system.created"
  | "system.profile-updated"
  | "system.deleted"
  | "group.created"
  | "group.updated"
  | "group.archived"
  | "group.restored"
  | "group.moved"
  | "group-membership.added"
  | "group-membership.removed"
  | "custom-front.created"
  | "custom-front.updated"
  | "custom-front.archived"
  | "custom-front.restored"
  | "group.deleted"
  | "custom-front.deleted"
  | "auth.biometric-enrolled"
  | "auth.biometric-verified"
  | "auth.biometric-failed"
  | "settings.pin-set"
  | "settings.pin-removed"
  | "settings.pin-verified"
  | "settings.nomenclature-updated"
  | "setup.step-completed"
  | "setup.completed"
  | "member.updated"
  | "member.duplicated"
  | "member.restored"
  | "member-photo.created"
  | "member-photo.archived"
  | "member-photo.restored"
  | "member-photo.reordered"
  | "field-definition.created"
  | "field-definition.updated"
  | "field-definition.archived"
  | "field-definition.restored"
  | "field-value.set"
  | "field-value.updated"
  | "field-value.deleted"
  | "structure-entity-type.created"
  | "structure-entity-type.updated"
  | "structure-entity-type.archived"
  | "structure-entity-type.restored"
  | "structure-entity-type.deleted"
  | "structure-entity.created"
  | "structure-entity.updated"
  | "structure-entity.archived"
  | "structure-entity.restored"
  | "structure-entity.deleted"
  | "relationship.created"
  | "relationship.updated"
  | "relationship.archived"
  | "relationship.restored"
  | "relationship.deleted"
  | "lifecycle-event.created"
  | "lifecycle-event.archived"
  | "lifecycle-event.restored"
  | "lifecycle-event.deleted"
  | "structure-entity-link.created"
  | "structure-entity-link.deleted"
  | "structure-entity-member-link.added"
  | "structure-entity-member-link.removed"
  | "structure-entity-association.created"
  | "structure-entity-association.deleted"
  | "innerworld-region.created"
  | "innerworld-region.updated"
  | "innerworld-region.archived"
  | "innerworld-region.restored"
  | "innerworld-region.deleted"
  | "innerworld-entity.created"
  | "innerworld-entity.updated"
  | "innerworld-entity.archived"
  | "innerworld-entity.restored"
  | "innerworld-entity.deleted"
  | "innerworld-canvas.created"
  | "innerworld-canvas.updated"
  | "blob.upload-requested"
  | "blob.confirmed"
  | "blob.archived"
  | "member.deleted"
  | "member-photo.deleted"
  | "field-definition.deleted"
  | "fronting-session.created"
  | "fronting-session.updated"
  | "fronting-session.ended"
  | "fronting-session.archived"
  | "fronting-session.restored"
  | "fronting-session.deleted"
  | "fronting-comment.created"
  | "fronting-comment.updated"
  | "fronting-comment.archived"
  | "fronting-comment.restored"
  | "fronting-comment.deleted"
  | "fronting-report.created"
  | "fronting-report.deleted"
  | "timer-config.created"
  | "timer-config.updated"
  | "timer-config.archived"
  | "timer-config.restored"
  | "timer-config.deleted"
  | "check-in-record.created"
  | "check-in-record.responded"
  | "check-in-record.dismissed"
  | "check-in-record.archived"
  | "check-in-record.deleted";

/** The actor who performed an audit-logged action. */
export type AuditActor =
  | { readonly kind: "account"; readonly id: AccountId }
  | { readonly kind: "api-key"; readonly id: ApiKeyId }
  | { readonly kind: "system"; readonly id: SystemId };

/** An append-only audit log entry. */
export interface AuditLogEntry {
  readonly id: AuditLogEntryId;
  readonly systemId: SystemId;
  readonly eventType: AuditEventType;
  readonly createdAt: UnixMillis;
  readonly actor: AuditActor;
  readonly detail: Plaintext<string> | null;
  readonly ipAddress: string | null;
  readonly userAgent: string | null;
}
